# Generated by Django 3.1.2 on 2020-10-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201030_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('photographer', models.CharField(max_length=100)),
                ('photographer_url', models.CharField(max_length=100)),
                ('src_medium', models.CharField(max_length=100)),
            ],
        ),
    ]
